ArcadiaEMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from asset.views import AssetIndexView
from .settings import DEBUG
from user import views as user_views
from django.conf import settings
from django.conf.urls.static import static

from .views import page_error, page_not_found

urlpatterns = \
    [
        path('user/', include('user.urls', namespace='user')),
        path('department/', include('department.urls', namespace='department')),
        path('asset/', include('asset.urls', namespace='asset')),
        path('review/', include('review.urls', namespace='review')),

        path('', AssetIndexView.as_view(), name='index'),
        path('login/', user_views.LoginView.as_view(), name='login'),
        path('logout/', user_views.LogoutView.as_view(), name='logout'),
        path('maintained/', auth_views.TemplateView.as_view(template_name='maintenance.html'),
             name='maintained'),
        path('faq/', user_views.FaqView.as_view(), name='faq'),
        path('admin/', admin.site.urls),
        # path('ui/', include('system.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found
handler500 = page_error

if DEBUG:
    urlpatterns += [
        path('404/', handler404, name='404'),
        path('500/', handler500, name='500'),
    ]

asset/urls.py
from django.urls import path

from asset.table_views import *
from asset.views import *

app_name = 'asset'

urlpatterns = [
    path('', AssetIndexView.as_view(), name='index'),
    path('mine/', AssetMineView.as_view(), name='mine'),

    path('<slug:asset_id>', AssetProfileView.as_view(), name='profile'),

    path('create/', AssetCreationView.as_view(), name='create'),
    path('create/<slug:asset_id>', AssetCreationOnAssetView.as_view(), name='create-on-asset'),

    path('borrow/<int:asset_set_id>', AssetBorrowView.as_view(), name='borrow'),
    path('return/', AssetReturnIndexView.as_view(), name='return-index'),
    # TODO: Why is this app_id while you actually deal with asset_set?
    path('return/<int:app_id>', AssetReturnView.as_view(), name='return'),

    path('scrap/<int:asset_set_id>', AssetScrapView.as_view(), name='scrap'),
    path('fix/<int:asset_set_id>', AssetFixView.as_view(), name='fix'),

    # 统计报表
    path('create-table/', AssetCreateTableView.as_view(), name='create-table'),
    path('scrap-table/', AssetScrapTableView.as_view(), name='scrap-table'),
    path('fix-table/', AssetFixTableView.as_view(), name='fix-table'),
    path('borrow-return-table/', AssetBorrowReturnTableView.as_view(), name='borrow-return-table')
]

user/urls.py
from django.urls import path

from user.views import *

app_name = 'user'

urlpatterns = [
    # path('user/', ),
    path('', UserIndexView.as_view(), name='index'),
    path('<int:user_id>', UserProfileView.as_view(), name='profile'),
    path('create-user/', UserCreateView.as_view(), name='create-user'),
    path('delete-user/<int:user_id>', DeleteUserView.as_view(), name='delete-user'),
    path('update-user/', UpdateUserView.as_view(), name='update-user'),

    path('toggle-user-status/<int:user_id>', ToggleUserStatusView().as_view(), name='toggle-user-status'),

    path('change-password/<int:user_id>', UserChangePasswordView.as_view(), name='change-password'),
    path('recover-password/', UserRecoverPasswordView.as_view(), name='recover-password'),

    path('calendar/', UserCalendarView.as_view(), name='calendar'),
    path('group/', UserGroupsView.as_view(), name='groups'),
    path('group/create', UserCreateGroupView.as_view(), name='create-group'),
    path('group/<int:group_id>/change', UserChangeGroupView.as_view(), name='change-group'),
    path('group/<int:group_id>/delete', UserDeleteGroupView.as_view(), name='delete-group'),
]

asset/views.py
import json
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views import View

from ArcadiaEMS.mixin import LoginRequiredMixin
from ArcadiaEMS.views import page_not_found
from asset.forms import AssetCreationForm, AssetForm, AssetSkuForm, AssetSetForm, AssetScrapForm, AssetBorrowForm, \
    AssetReturnForm, AssetFixForm
from asset.models import Asset, AssetSet, AssetBorrowReturn, BaseApp
from asset.serializers import AssetSkuSerializer, AssetSerializer, \
    BaseAppSerializer, AssetSetSerializer


class AssetIndexView(LoginRequiredMixin, View):

    def get(self, request):
        assets = Asset.objects.all()
        return render(request, 'assets.html', {'assets': assets})

    def post(self, request):
        if request.is_ajax():
            assets = AssetSerializer(instance=Asset.objects.all(), many=True)
            return HttpResponse(json.dumps(assets.data), content_type='application/json')
        else:
            assets = Asset.objects.all()
            return render(request, 'assets.html', {'assets': assets})


class AssetMineView(LoginRequiredMixin, View):

    def get(self, request):
        return render(request, 'mine.html')

    def post(self, request):
        if request.is_ajax():
            apps = BaseApp.objects.filter(transactor=request.user)
            apps_ = BaseAppSerializer(instance=apps, many=True)
            return HttpResponse(json.dumps(apps_.data), content_type='application/json')


class AssetProfileView(LoginRequiredMixin, View):

    def get(self, request, asset_id):
        asset = get_object_or_404(Asset, pk=asset_id)
        # Sum all stocks under this asset
        stock = 0
        for skus in asset.skus.all():
            for set in skus.sets.all():
                stock += set.quantity
        return render(request, 'profile.html', {'asset': asset, 'stock': stock})

    def post(self, request, asset_id):
        if request.is_ajax():
            asset = get_object_or_404(Asset, pk=asset_id)
            skus = AssetSkuSerializer(instance=asset.skus.all(), many=True)
            return HttpResponse(json.dumps(skus.data), content_type='application/json')
        else:
            raise page_not_found(request)


class AssetCreationView(LoginRequiredMixin, View):

    def get(self, request):
        if request.is_ajax():
            assets = AssetSerializer(instance=Asset.objects.all(), many=True)
            return HttpResponse(json.dumps(assets.data), content_type='application/json')
        else:
            asset_creation_form = AssetCreationForm(auto_id="form-asset-create-%s", label_suffix='')
            asset_form = AssetForm(auto_id="form-asset-%s", label_suffix='')
            asset_sku_form = AssetSkuForm(auto_id="form-asset-sku-%s", label_suffix='')
            asset_set_form = AssetSetForm(auto_id="form-asset-set-%s", label_suffix='')
            ret = {
                'asset_creation_form': asset_creation_form,
                'asset_form': asset_form,
                'asset_sku_form': asset_sku_form,
                'asset_set_form': asset_set_form,
            }
            return render(request, 'create-asset.html', ret)

    def post(self, request):
        asset_form = AssetForm(request.POST, auto_id="form-asset-%s", label_suffix='')
        asset_sku_form = AssetSkuForm(request.POST, auto_id="form-asset-sku-%s", label_suffix='')
        asset_set_form = AssetSetForm(request.POST, auto_id="form-asset-set-%s", label_suffix='')
        asset_creation_form = AssetCreationForm(request.POST, auto_id="form-asset-create-%s", label_suffix='')
        ret = {
            'asset_creation_form': asset_creation_form,
            'asset_form': asset_form,
            'asset_sku_form': asset_sku_form,
            'asset_set_form': asset_set_form,
        }
        save_ret = save_asset_creation(asset_form, asset_sku_form, asset_set_form,
                                       asset_creation_form)
        if save_ret and save_ret.get('asset'):
            asset = save_ret.get('asset')
            ret.update({'msg': '编号【%s】设备的建账申请已提交！' % asset})
        elif save_ret.get('error_msg'):
            ret.update(save_ret)
        return render(request, 'create-asset.html', ret)


class AssetCreationOnAssetView(LoginRequiredMixin, View):

    def get(self, request, asset_id):
        asset = get_object_or_404(Asset, pk=asset_id)
        asset_creation_form = AssetCreationForm(auto_id="form-asset-create-%s", label_suffix='')
        asset_form = AssetForm(instance=asset, auto_id="form-asset-%s", label_suffix='')
        asset_sku_form = AssetSkuForm(auto_id="form-asset-sku-%s", label_suffix='')
        asset_set_form = AssetSetForm(auto_id="form-asset-set-%s", label_suffix='')
        ret = {
            'asset_creation_form': asset_creation_form,
            'asset_form': asset_form,
            'asset_sku_form': asset_sku_form,
            'asset_set_form': asset_set_form,
            'asset': asset,
            'readonly': True,
        }
        return render(request, 'create-asset.html', ret)

    def post(self, request, asset_id):
        asset = get_object_or_404(Asset, pk=asset_id)
        asset_form = AssetForm(auto_id="form-asset-%s", label_suffix='')
        asset_creation_form = AssetCreationForm(request.POST, auto_id="form-create-%s", label_suffix='')
        asset_sku_form = AssetSkuForm(request.POST, auto_id="form-asset-sku-%s", label_suffix='')
        asset_set_form = AssetSetForm(request.POST, auto_id="form-asset-set-%s", label_suffix='')
        ret = {
            'asset_creation_form': asset_creation_form,
            'asset_sku_form': asset_sku_form,
            'asset_set_form': asset_set_form,
            'readonly': True,
            'asset': asset,
            'asset_form': asset_form,
        }
        save_ret = save_asset_creation(asset_form, asset_sku_form, asset_set_form,
                                       asset_creation_form, on_asset=True, asset=asset)
        if save_ret and save_ret.get('asset') is not None:
            ret.update({'msg': '基于编号【{}】设备的建账申请已提交！'.format(asset.aid)})
        elif save_ret.get('error_msg'):
            ret.update(save_ret)
        return render(request, 'create-asset.html', ret)


def save_asset_creation(asset_form, asset_sku_form, asset_set_form, asset_creation_form, on_asset=False, asset=None):
    if asset_sku_form.is_valid() and asset_set_form.is_valid() and asset_creation_form.is_valid():
        if not on_asset and asset is None:
            if asset_form.is_valid():
                asset = asset_form.save()
            else:
                return asset_form.errors
        asset_sku = asset_sku_form.save(asset)
        asset_creation = asset_creation_form.save(sku=asset_sku)
        asset_set_form.save(sku=asset_sku, app=asset_creation)
        return {'asset': asset.aid}
    else:
        if not on_asset and asset_form.errors:
            errors = asset_form.errors
        elif asset_creation_form.errors:
            errors = asset_creation_form.errors
        elif asset_sku_form.errors:
            errors = asset_sku_form.errors
        elif asset_set_form.errors:
            errors = asset_set_form.errors
        else:
            return {'error_msg': 'Unknown errors'}
        return {'error_msg': errors.as_ul()}


class AssetFixView(LoginRequiredMixin, View):

    def get(self, request, asset_set_id):
        fix_form = AssetFixForm(auto_id="form-fix-%s", label_suffix='')
        asset_set_child_form = AssetSetForm(auto_id='form-asset-set-%s', label_suffix='')
        asset_set = get_object_or_404(AssetSet, pk=asset_set_id)
        ret = {
            'fix_form': fix_form,
            'asset_set': asset_set,
            'asset_set_form': asset_set_child_form,
        }
        return render(request, 'asset-fix.html', ret)

    def post(self, request, asset_set_id):
        asset_set = get_object_or_404(AssetSet, pk=asset_set_id)
        asset_sku = asset_set.sku
        asset = asset_sku.asset

        fix_form = AssetFixForm(request.POST, auto_id="form-fix-%s", label_suffix='')
        asset_set_new_form = AssetSetForm(request.POST, auto_id="form-asset-new-%s", label_suffix='')
        ret = {
            'fix_form': fix_form,
            'asset_set': asset_set,
            'asset_set_form': asset_set_new_form,
        }
        if fix_form.is_valid() and asset_set_new_form.is_valid():
            # if fixing the whole set
            child_quantity = asset_set_new_form.cleaned_data.get('quantity')
            if child_quantity == asset_set.quantity:
                # Abandon the forked asset set form
                asset_set.status = '报修审核中'
                asset_set.save()
                fix_app = fix_form.save(sku=asset_sku)
                ret.update({'msg': '编号【{}】设备报修申请已提交！'.format(fix_app.id)})
            elif child_quantity > asset_set.quantity:
                ret.update({
                    'error_msg': '数量超过了合法范围'
                })
            else:
                asset_set.quantity -= child_quantity
                asset_set.save()

                fix_app = fix_form.save(sku=asset_sku)

                asset_set_new_form.save(sku=asset_sku, app=fix_app)

                ret.update({'msg': '编号【{}】设备报修申请已提交！'.format(fix_app.id)})
        elif fix_form.errors:
            ret.update({
                'error_msg': fix_form.errors.as_ul()
            })
        else:
            ret.update({
                'error_msg': asset_set_new_form.errors.as_ul()
            })
        return render(request, 'asset-fix.html', ret)


class AssetScrapView(LoginRequiredMixin, View):

    def get(self, request, asset_set_id):
        scrap_form = AssetScrapForm(auto_id="form-scrap-%s", label_suffix='')
        asset_set_child_form = AssetSetForm(auto_id='form-asset-set-%s', label_suffix='')
        asset_set = get_object_or_404(AssetSet, pk=asset_set_id)
        ret = {
            'scrap_form': scrap_form,

asset/templates/asset.html
{% extends "base-sidebar.html" %}
{% load static %}

{% block css %}
    <!-- third party css -->
    <link href="{% static 'css/dataTables.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <!-- third party css end -->
{% endblock %}

{% block content %}
    <!-- Start Content-->
    <div class="container-fluid">
        {% include 'base-page-title.html' with title_name='设备台账' %}

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">

                        <div class="row mb-2">
                            <div class="col-sm-4">
                                <a href="{% url 'asset:create' %}" class="btn btn-danger mb-2 badge-l">
                                    <i class="mdi mdi-plus-circle mr-1"></i> 设备建账</a>
                            </div>
                            <div class="col-sm-8">
                                <div class="text-sm-right">
                                    <button disabled type="button" class="btn btn-warning mb-3 mr-1">
                                        Export
                                    </button>
                                    <button type="button" class="btn btn-info dt-btn-reload mb-3">
                                        <i class="mdi mdi-refresh"></i>
                                    </button>
                                </div>
                            </div><!-- end col-->
                        </div>
                        <table id="datatable-assets" class="table table-striped dt-responsive nowrap"></table>
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col -->
        </div>
        <!-- end row-->
    </div> <!-- container -->
{% endblock %}


{% block javascripts %}

{% endblock %}

{% block js-footer %}
    <!-- third party js -->
    <script src="{% static 'javascript/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'javascript/dataTables.bootstrap4.js' %}"></script>
    <script src="{% static 'javascript/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'javascript/responsive.bootstrap4.min.js' %}"></script>
    <!-- third party js ends -->

    <!-- demo app -->
    <script src="{% static 'javascript/arcadia.datatable.js' %}"></script>
    <!-- end demo js-->
    <script src="{% static 'javascript/arcadia.datatable.asset.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            // "use strict";
            initDatatable($('#datatable-assets'), "{% url 'asset:index' %}", "{{ csrf_token }}");
        });
    </script>
{% endblock %}

asset/templates/assets.html
{% extends "base-sidebar.html" %}
{% load static %}

{% block css %}
    <!-- third party css -->
    <link href="{% static 'css/dataTables.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <!-- third party css end -->
{% endblock %}

{% block content %}
    <!-- Start Content-->
    <div class="container-fluid">
        {% include 'base-page-title.html' with title_name='设备台账' %}

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">

                        <div class="row mb-2">
                            <div class="col-sm-4">
                                <a href="{% url 'asset:create' %}" class="btn btn-danger mb-2 badge-l">
                                    <i class="mdi mdi-plus-circle mr-1"></i> 设备建账</a>
                            </div>
                            <div class="col-sm-8">
                                <div class="text-sm-right">
                                    <button disabled type="button" class="btn btn-warning mb-3 mr-1">
                                        Export
                                    </button>
                                    <button type="button" class="btn btn-info dt-btn-reload mb-3">
                                        <i class="mdi mdi-refresh"></i>
                                    </button>
                                </div>
                            </div><!-- end col-->
                        </div>
                        <table id="datatable-assets" class="table table-striped dt-responsive nowrap"></table>
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col -->
        </div>
        <!-- end row-->
    </div> <!-- container -->
{% endblock %}


{% block javascripts %}

{% endblock %}

{% block js-footer %}
    <!-- third party js -->
    <script src="{% static 'javascript/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'javascript/dataTables.bootstrap4.js' %}"></script>
    <script src="{% static 'javascript/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'javascript/responsive.bootstrap4.min.js' %}"></script>
    <!-- third party js ends -->

    <!-- demo app -->
    <script src="{% static 'javascript/arcadia.datatable.js' %}"></script>
    <!-- end demo js-->
    <script src="{% static 'javascript/arcadia.datatable.asset.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            // "use strict";
            initDatatable($('#datatable-assets'), "{% url 'asset:index' %}", "{{ csrf_token }}");
        });
    </script>
{% endblock %}

asset/templates/create-asset.html
{% extends 'base-sidebar.html' %}
{% load static %}

{% block css %}
    <!-- third party css -->
    <link href="{% static 'css/dataTables.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <!-- third party css end -->
{% endblock %}

{% block content %}
    <!-- Start Content-->
    <div class="container-fluid">
        {% include 'base-page-title.html' with title_name='设备建账' %}
        {% if msg %}
            <div class="alert alert-success" role="alert">
                {{ msg }}
            </div>
        {% endif %}
        <div class="row">
            <div class="col-12">
                <div class="card card-body">
                    <div class="row">
                        <div class="col-lg-8">
                            {% include 'form-create-asset.html' %}
                        </div>
                        <div class="col-lg-4">
                            <a href="{% url 'asset:create' %}" type="button" class="btn btn-info mt-3">
                                <i class="mdi mdi-keyboard-return mr-1"></i> 新建设备（清空）
                            </a>
                            <div class="border p-3 mt-4 rounded">
                                <h4 class="header-title mb-3">基于现有设备新建货格：</h4>
                                <table id="datatable-create-asset" class="table table-striped dt-responsive nowrap">
                                </table>
                            </div>
                            <!-- end table-responsive -->
                        </div> <!-- end .border-->
                    </div> <!-- end col -->
                </div> <!-- end card-body-->
            </div> <!-- end card-->
        </div> <!-- end col -->
    </div>
    <!-- end row-->
{% endblock %}

{% block js-footer %}
    <!-- third party js -->
    <script src="{% static 'javascript/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'javascript/dataTables.bootstrap4.js' %}"></script>
    <script src="{% static 'javascript/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'javascript/responsive.bootstrap4.min.js' %}"></script>
    <!-- third party js ends -->

    <!-- demo app -->
    <script src="{% static 'javascript/arcadia.datatable.js' %}"></script>
    <script src="{% static 'javascript/arcadia.datatable.asset.js' %}"></script>
    <!-- end demo js-->

    <script type="text/javascript">
        $(document).ready(function () {
            initDatatable(
                $('#datatable-create-asset'),
                "{% url 'asset:index' %}",
                "{{ csrf_token }}",
                paging = false,
                searching = false,
            );
        });
    </script>
{% endblock %}

asset/templates/form-borrow-asset.html
{% if asset_set %}
    <form action="{% url 'asset:borrow' asset_set.id %}" method="post" class="pl-2 pr-2">
        {% csrf_token %}
        <h4 class="mt-4">借出信息</h4>
        <p class="text-muted mb-4">借出具体数量，预计归还日期等必要信息</p>
        {{ borrow_form }}
        {{ asset_set_form }}
        {% if error_msg %}
            <div class="alert alert-warning">{{ error_msg }}</div>
        {% endif %}
        {% if not nofooter %}
            <div class="row mt-4">
                <div class="col-sm-6">
                    <a href="{% url 'asset:index' %}"
                       class="btn text-muted d-none d-sm-inline-block btn-link font-weight-semibold">
                        <i class="mdi mdi-arrow-left"></i> 返回台账
                    </a>
                </div> <!-- end col -->
                <div class="col-sm-6 text-sm-right">
                    <button type="submit" class="btn btn-danger">
                        <i class="mdi mdi-truck-fast mr-1"></i> 提交
                    </button>
                </div> <!-- end col -->
            </div> <!-- end row -->
        {% endif %}
    </form>
{% else %}
    <div class="alert alert-danger">该设备组已失效，原因可能是已经被合入了</div>
{% endif %}

asset/templates/profile.html
{% extends "base-sidebar.html" %}
{% load static %}

{% block css %}
    <!-- third party css -->
    <link href="{% static 'css/dataTables.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/buttons.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/select.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <!-- third party css end -->
{% endblock %}

{% block content %}
    <!-- Start Content-->
    <div class="container-fluid">
        {% include 'base-page-title.html' with title_name='设备详情' sec_title='设备台账' sec_url='/asset/' %}

        <div class="row">
            <div class="col-10">
                <div class="card card-body">
                    <div class="row">
                        <div class="col-lg-5">
                            <!-- Product image -->
                            <img src="{% static 'htmlimg/small-2.jpg' %}"
                                 class="img-fluid" alt="Product-img">
                        </div> <!-- end col -->
                        <div class="col-lg-7">
                            <h3 class="mt-3">{{ asset.name }}</h3>
                            <p class="text-muted">{{ asset.aid }}</p>
                            <!-- Product stock -->
                            <div class="mt-2 mb-3">
                                <h3><span class="badge badge-info">{{ asset.status }}</span></h3>
                            </div>

                            <div class="row">
                                <div class="col-lg-5">
                                    <h5 class="mt-1">购置日期: </h5>
                                    <span> {{ asset.created_at }}</span>
                                </div>
                                <div class="col-lg-5">
                                    <h5 class="mt-1">最近更新日期: </h5>
                                    <span> {{ asset.updated_at }}</span>
                                </div>
                            </div>
                            <div class="mt-3">
                                <h5>所属类别: </h5>
                                <span>{{ asset.category }}</span>
                            </div>
                            <!-- Product information -->
                            <div class="mt-3">
                                <div class="row">
                                    <div class="col-md-4">
                                        <h5>库存容量:</h5>
                                        <h5>{{ stock }}</h5>
                                    </div>
                                    <div class="col-md-4">
                                        <h5>SKU统计:</h5>
                                        <h5>{{ asset.skus.all.count }}</h5>
                                    </div>
                                </div>
                            </div>
                            <!-- Product description -->
                            <div class="mt-3 mb-4">
                                <h5>设备描述:</h5>
                                <p class="text font-15">
                                    {% if asset.description %}
                                        {{ asset.description }}
                                    {% else %}
                                        No description.
                                    {% endif %}
                                </p>
                            </div>
                        </div> <!-- end col -->
                    </div> <!-- end row-->

                    <table id="datatable-asset-skus"
                           class="table table-bordered table-striped nowrap"></table>

                    <div class="mt-4">
                        {% for sku in asset.skus.all %}
                            <div class="collapse" id="asset-sets-{{ sku.id }}">
                                <table class="table table-bordered dt-responsive nowrap">
                                    <thead class="thead-light">
                                    <tr>
                                        <th>ID</th>
                                        <th>所在部门</th>
                                        <th>详细位置</th>
                                        <th>负责人</th>
                                        <th>存货量</th>
                                        <th>状态</th>
                                        <th>操作</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for asset_set in sku.sets.all %}
                                        <tr>
                                            <td>{{ asset_set.id }}</td>
                                            <td>{{ asset_set.department }}</td>
                                            <td>{{ asset_set.address }}</td>
                                            <td>{{ asset_set.manager }}</td>
                                            <td>{{ asset_set.quantity }}</td>
                                            <td>{{ asset_set.status }}</td>
                                            <td>
                                                {% if asset_set.status|slice:"2:" != "审核中" %}
                                                    <a href="{% url 'asset:borrow' asset_set.id %}" class='action-icon'>
                                                        <i class='mdi mdi-cart'></i>借出</a>
                                                    <a href="{% url 'asset:scrap' asset_set.id %}" class='action-icon'>
                                                        <i class='mdi mdi-image-broken'></i>报废</a>
                                                    <a href="{% url 'asset:fix' asset_set.id %}" class='action-icon'>
                                                        <i class='mdi mdi-auto-fix'></i>报修</a>
                                                {% else %}
                                                    业务办理中不予操作
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        {% endfor %}

                    </div> <!-- end row-->

                </div> <!-- end card-->
            </div> <!-- end col -->

            <div class="col-2">
                <div class="card card-body">
                    <h3>Record</h3>
                    <p>timeline here</p>
                </div>
            </div>
        </div>
        <!-- end row-->
    </div> <!-- container -->
{% endblock %}


{% block javascripts %}
{% endblock %}

{% block js-footer %}
    <!-- third party js -->
    <script src="{% static 'javascript/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'javascript/dataTables.bootstrap4.js' %}"></script>
    <script src="{% static 'javascript/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'javascript/responsive.bootstrap4.min.js' %}"></script>
    <!-- third party js ends -->
    <script src="{% static 'javascript/arcadia.datatable.js' %}"></script>
    <script src="{% static 'javascript/arcadia.datatable.asset_skus.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            // "use strict";
            initDatatable($('#datatable-asset-skus'), "{% url 'asset:profile' asset.aid %}", "{{ csrf_token }}");
        });
    </script>
{% endblock %}