ArcadiaEMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from asset.views import AssetIndexView
from .settings import DEBUG
from user import views as user_views
from django.conf import settings
from django.conf.urls.static import static

from .views import page_error, page_not_found

urlpatterns = \
    [
        path('user/', include('user.urls', namespace='user')),
        path('department/', include('department.urls', namespace='department')),
        path('asset/', include('asset.urls', namespace='asset')),
        path('review/', include('review.urls', namespace='review')),

        path('', AssetIndexView.as_view(), name='index'),
        path('login/', user_views.LoginView.as_view(), name='login'),
        path('logout/', user_views.LogoutView.as_view(), name='logout'),
        path('maintained/', auth_views.TemplateView.as_view(template_name='maintenance.html'),
             name='maintained'),
        path('faq/', user_views.FaqView.as_view(), name='faq'),
        path('admin/', admin.site.urls),
        # path('ui/', include('system.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found
handler500 = page_error

if DEBUG:
    urlpatterns += [
        path('404/', handler404, name='404'),
        path('500/', handler500, name='500'),
    ]

department/urls.py
from django.urls import path

from .views import *

app_name = 'department'

urlpatterns = [
    path('', DepartmentsView.as_view(), name='index'),
    path('create/', DepartmentCreationView.as_view(), name='create'),
    path('delete/<int:department_id>', DepartmentDeleteView.as_view(), name='delete'),
    path('change/<int:department_id>', DepartmentChangeView.as_view(), name='change'),

]

user/urls.py
from django.urls import path

from user.views import *

app_name = 'user'

urlpatterns = [
    # path('user/', ),
    path('', UserIndexView.as_view(), name='index'),
    path('<int:user_id>', UserProfileView.as_view(), name='profile'),
    path('create-user/', UserCreateView.as_view(), name='create-user'),
    path('delete-user/<int:user_id>', DeleteUserView.as_view(), name='delete-user'),
    path('update-user/', UpdateUserView.as_view(), name='update-user'),

    path('toggle-user-status/<int:user_id>', ToggleUserStatusView().as_view(), name='toggle-user-status'),

    path('change-password/<int:user_id>', UserChangePasswordView.as_view(), name='change-password'),
    path('recover-password/', UserRecoverPasswordView.as_view(), name='recover-password'),

    path('calendar/', UserCalendarView.as_view(), name='calendar'),
    path('group/', UserGroupsView.as_view(), name='groups'),
    path('group/create', UserCreateGroupView.as_view(), name='create-group'),
    path('group/<int:group_id>/change', UserChangeGroupView.as_view(), name='change-group'),
    path('group/<int:group_id>/delete', UserDeleteGroupView.as_view(), name='delete-group'),
]

department/models.py
from django.db import models


class Department(models.Model):
    name = models.CharField(max_length=30, null=True, unique=True, verbose_name='部门')

    class Meta:
        verbose_name = "Department"
        verbose_name_plural = "Departments"
        ordering = ['id']

    def __str__(self):
        return self.name.__str__()

department/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.forms import TextInput, Select, EmailInput, SelectMultiple

from .models import Department


class DepartmentCreationForm(forms.ModelForm):
    name = forms.CharField(
        label="Department Name",
        required=True,
        widget=TextInput(attrs={'class': 'form-control', 'placeholder': "Department Name"}, )
    )

    class Meta:
        model = Department
        fields = ['name']

department/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View

from ArcadiaEMS.mixin import LoginRequiredMixin
from .forms import DepartmentCreationForm
from .models import Department


class DepartmentsView(LoginRequiredMixin, View):

    def get(self, request):
        departments = Department.objects.all()
        return render(request, 'department/index.html', {'departments': departments})


class DepartmentCreationView(LoginRequiredMixin, View):

    def get(self, request):
        dc_form = DepartmentCreationForm()
        return render(request, 'department/create-department.html', {'dc_form': dc_form})

    def post(self, request):
        dc_form = DepartmentCreationForm(request.POST)
        if dc_form.is_valid():
            department = dc_form.save()
            ret = {
                'dc_form': dc_form,
                'msg': 'Successfully created department ' + department.name
            }
        else:
            ret = {
                'dc_form': dc_form,
                'error_msg': dc_form.errors.as_text(),
            }
        return render(request, 'department/create-department.html', ret)


class DepartmentChangeView(LoginRequiredMixin, View):

    def get(self, request, department_id):
        department = get_object_or_404(Department, pk=department_id)
        form = DepartmentCreationForm(instance=department)
        ret = {
            'department': department,
            'form': form,
        }
        return render(request, 'department/change-department.html', ret)

    def post(self, request, department_id):
        department = get_object_or_404(Department, pk=department_id)
        form = DepartmentCreationForm(request.POST, instance=department)
        if form.is_valid():
            form.save()
            ret = {
                "msg": "Successfully Changed Department " + department.name,
                'department': department,
                'form': form,
            }
        else:
            ret = {
                'error_msg': form.errors.as_ul(),
                'department': department,
                'form': form,
            }
        return render(request, 'department/change-department.html', ret)


class DepartmentDeleteView(LoginRequiredMixin, View):

    def get(self, request, department_id):
        if department_id and department_id > 0:
            Department.objects.filter(id=department_id).delete()
        return redirect('department:index')

templates/department/change-department.html
{% extends 'base-sidebar.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid">
        {% include 'base-page-title.html' with title_name='Change Department' sec_title="Departments" sec_url="/department/" %}
        {% if msg %}
            <div class="alert alert-success" role="alert">
                {{ msg }}
            </div>
        {% endif %}
        <div class="row">
            <div class="col-sm-6">
                <div class="card card-body">
                    <form action="{% url 'department:change' department.id %}" method="post" class="pl-3 pr-3">
                        {% csrf_token %}
                        <div class="form-group mb-3">
                            {{ form.name.label_tag }}
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="inputGroupPrepend">@</span>
                                </div>
                                {{ form.name }}
                            </div>
                        </div>
                        {% if error_msg %}
                            <p class="alert alert-warning">{{ error_msg }}</p>
                        {% endif %}
                        <div class="text-center">
                            <button class="btn btn-primary" type="submit">Change Department</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/department/create-department.html
{% extends 'base-sidebar.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid">
        {% include 'base-page-title.html' with title_name='Create Department' sec_title="Departments" sec_url="/department/" %}
        {% if msg %}
            <div class="alert alert-success" role="alert">
                {{ msg }}
            </div>
        {% endif %}
        <div class="row">
            <div class="col-sm-6">
                <div class="card card-body">
                    <form action="{% url 'department:create' %}" method="post" class="pl-3 pr-3">
                        {% csrf_token %}
                        <div class="form-group mb-3">
                            {{ dc_form.name.label_tag }}
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="inputGroupPrepend">@</span>
                                </div>
                                {{ dc_form.name }}
                            </div>
                        </div>
                        {% if error_msg %}
                            <p class="alert alert-warning">{{ error_msg }}</p>
                        {% endif %}
                        <div class="text-center">
                            <button class="btn btn-primary" type="submit">Create Department</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/department/index.html
{% extends "base-sidebar.html" %}
{% load static %}

{% block css %}
    <!-- third party css -->
    <link href="{% static 'css/dataTables.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/buttons.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/select.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <!-- third party css end -->
{% endblock %}

{% block content %}
    <!-- Start Content-->
    <div class="container-fluid">
        {% include 'base-page-title.html' with title_name='Departments' %}

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <a href="{% url 'department:create' %}" type="button" class="btn btn-primary mb-3">
                            <i class="mdi mdi-account-multiple-plus mr-1"></i> New Department
                        </a>

                        <table id="basic-datatable" class="table table-striped dt-responsive nowrap">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Users</th>
                                <th>Action</th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for department in departments %}
                                <tr>
                                    <td>{{ department.id }}</td>
                                    <td>{{ department.name }}</td>
                                    <td>
                                        {% for user in department.users.all %}
                                            {{ user }}
                                        {% endfor %}
                                    </td>
                                    <td class="table-action">
                                        <a href="{% url 'department:change' department.id %}" class="action-icon">
                                            <i class="mdi mdi-pencil"></i></a>
                                        <a href="{% url 'department:delete' department.id %}" class="action-icon">
                                            <i class="mdi mdi-delete"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div> <!-- end card body-->
                </div> <!-- end card -->
            </div><!-- end col-->
        </div>
        <!-- end row-->
    </div> <!-- container -->
{% endblock %}


{% block js-footer %}
    <!-- third party js -->
    <script src="{% static 'javascript/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'javascript/dataTables.bootstrap4.js' %}"></script>
    <script src="{% static 'javascript/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'javascript/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'javascript/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'javascript/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'javascript/buttons.html5.min.js' %}"></script>
    <script src="{% static 'javascript/buttons.flash.min.js' %}"></script>
    <script src="{% static 'javascript/buttons.print.min.js' %}"></script>
    <script src="{% static 'javascript/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'javascript/dataTables.select.min.js' %}"></script>
    <!-- third party js ends -->

    <!-- demo app -->
    <script src="{% static 'javascript/demo.datatable-init2.js' %}"></script>
    <!-- end demo js-->
{% endblock %}