ArcadiaEMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from asset.views import AssetIndexView
from .settings import DEBUG
from user import views as user_views
from django.conf import settings
from django.conf.urls.static import static

from .views import page_error, page_not_found

urlpatterns = \
    [
        path('user/', include('user.urls', namespace='user')),
        path('department/', include('department.urls', namespace='department')),
        path('asset/', include('asset.urls', namespace='asset')),
        path('review/', include('review.urls', namespace='review')),

        path('', AssetIndexView.as_view(), name='index'),
        path('login/', user_views.LoginView.as_view(), name='login'),
        path('logout/', user_views.LogoutView.as_view(), name='logout'),
        path('maintained/', auth_views.TemplateView.as_view(template_name='maintenance.html'),
             name='maintained'),
        path('faq/', user_views.FaqView.as_view(), name='faq'),
        path('admin/', admin.site.urls),
        # path('ui/', include('system.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found
handler500 = page_error

if DEBUG:
    urlpatterns += [
        path('404/', handler404, name='404'),
        path('500/', handler500, name='500'),
    ]

asset/urls.py
from django.urls import path

from asset.table_views import *
from asset.views import *

app_name = 'asset'

urlpatterns = [
    path('', AssetIndexView.as_view(), name='index'),
    path('mine/', AssetMineView.as_view(), name='mine'),

    path('<slug:asset_id>', AssetProfileView.as_view(), name='profile'),

    path('create/', AssetCreationView.as_view(), name='create'),
    path('create/<slug:asset_id>', AssetCreationOnAssetView.as_view(), name='create-on-asset'),

    path('borrow/<int:asset_set_id>', AssetBorrowView.as_view(), name='borrow'),
    path('return/', AssetReturnIndexView.as_view(), name='return-index'),
    # TODO: Why is this app_id while you actually deal with asset_set?
    path('return/<int:app_id>', AssetReturnView.as_view(), name='return'),

    path('scrap/<int:asset_set_id>', AssetScrapView.as_view(), name='scrap'),
    path('fix/<int:asset_set_id>', AssetFixView.as_view(), name='fix'),

    # 统计报表
    path('create-table/', AssetCreateTableView.as_view(), name='create-table'),
    path('scrap-table/', AssetScrapTableView.as_view(), name='scrap-table'),
    path('fix-table/', AssetFixTableView.as_view(), name='fix-table'),
    path('borrow-return-table/', AssetBorrowReturnTableView.as_view(), name='borrow-return-table')
]

user/urls.py
from django.urls import path

from user.views import *

app_name = 'user'

urlpatterns = [
    # path('user/', ),
    path('', UserIndexView.as_view(), name='index'),
    path('<int:user_id>', UserProfileView.as_view(), name='profile'),
    path('create-user/', UserCreateView.as_view(), name='create-user'),
    path('delete-user/<int:user_id>', DeleteUserView.as_view(), name='delete-user'),
    path('update-user/', UpdateUserView.as_view(), name='update-user'),

    path('toggle-user-status/<int:user_id>', ToggleUserStatusView().as_view(), name='toggle-user-status'),

    path('change-password/<int:user_id>', UserChangePasswordView.as_view(), name='change-password'),
    path('recover-password/', UserRecoverPasswordView.as_view(), name='recover-password'),

    path('calendar/', UserCalendarView.as_view(), name='calendar'),
    path('group/', UserGroupsView.as_view(), name='groups'),
    path('group/create', UserCreateGroupView.as_view(), name='create-group'),
    path('group/<int:group_id>/change', UserChangeGroupView.as_view(), name='change-group'),
    path('group/<int:group_id>/delete', UserDeleteGroupView.as_view(), name='delete-group'),
]

templates/apps-calendar.html
{% extends 'base-sidebar.html' %}

{% load static %}

{% block css %}
    <!-- third party css -->
    <link href="{% static 'css/fullcalendar.min.css' %}" rel="stylesheet" type="text/css"/>
    <!-- third party css end -->
{% endblock %}

{% block content %}
    <!-- Start Content-->
    <div class="container-fluid">
        {% include 'base-page-title.html' with title_name='Calendar' %}

        <div class="row">
            <div class="col-12">

                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-3">
                                <a href="" data-toggle="modal" data-target="#add-category"
                                   class="btn btn-lg font-16 btn-primary btn-block  ">
                                    <i class="mdi mdi-plus-circle-outline"></i> Create New Event
                                </a>
                                <div id="external-events" class="m-t-20">
                                    <br>
                                    <p class="text-muted">Drag and drop your event or click in the calendar</p>
                                    <div class="external-event bg-success" data-class="bg-success">
                                        <i class="mdi mdi-checkbox-blank-circle mr-2 vertical-middle"></i>New
                                        Theme Release
                                    </div>
                                    <div class="external-event bg-info" data-class="bg-info">
                                        <i class="mdi mdi-checkbox-blank-circle mr-2 vertical-middle"></i>My
                                        Event
                                    </div>
                                    <div class="external-event bg-warning" data-class="bg-warning">
                                        <i class="mdi mdi-checkbox-blank-circle mr-2 vertical-middle"></i>Meet
                                        manager
                                    </div>
                                    <div class="external-event bg-danger" data-class="bg-danger">
                                        <i class="mdi mdi-checkbox-blank-circle mr-2 vertical-middle"></i>Create
                                        New theme
                                    </div>
                                </div>

                                <!-- checkbox -->
                                <div class="custom-control custom-checkbox mt-3">
                                    <input type="checkbox" class="custom-control-input" id="drop-remove">
                                    <label class="custom-control-label" for="drop-remove">Remove after
                                        drop</label>
                                </div>

                                <div class="mt-5 d-none d-xl-block">
                                    <h5 hidden class="text-center">How It Works ?</h5>
                                </div>
                            </div> <!-- end col-->

                            <div class="col-lg-9">
                                <div id="calendar"></div>
                            </div> <!-- end col -->

                        </div>  <!-- end row -->
                    </div> <!-- end card body-->
                </div> <!-- end card -->

                <!-- Add New Event MODAL -->
                <div class="modal fade" id="event-modal" tabindex="-1">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header pr-4 pl-4 border-bottom-0 d-block">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                    &times;
                                </button>
                                <h4 class="modal-title">Add New Event</h4>
                            </div>
                            <div class="modal-body pt-3 pr-4 pl-4">
                            </div>
                            <div class="text-right pb-4 pr-4">
                                <button type="button" class="btn btn-light " data-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-success save-event  ">Create event</button>
                                <button type="button" class="btn btn-danger delete-event  "
                                        data-dismiss="modal">Delete
                                </button>
                            </div>
                        </div> <!-- end modal-content-->
                    </div> <!-- end modal dialog-->
                </div>
                <!-- end modal-->

                <!-- Modal Add Category -->
                <div class="modal fade" id="add-category" tabindex="-1">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header border-bottom-0 d-block">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                    &times;
                                </button>
                                <h4 class="modal-title">Add a category</h4>
                            </div>
                            <div class="modal-body p-4">
                                <form>
                                    <div class="form-group">
                                        <label class="control-label">Category Name</label>
                                        <input class="form-control form-white" placeholder="Enter name"
                                               type="text" name="category-name"/>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Choose Category Color</label>
                                        <select class="form-control form-white"
                                                data-placeholder="Choose a color..." name="category-color">
                                            <option value="primary">Primary</option>
                                            <option value="success">Success</option>
                                            <option value="danger">Danger</option>
                                            <option value="info">Info</option>
                                            <option value="warning">Warning</option>
                                            <option value="dark">Dark</option>
                                        </select>
                                    </div>

                                </form>

                                <div class="text-right">
                                    <button type="button" class="btn btn-light " data-dismiss="modal">Close
                                    </button>
                                    <button type="button" class="btn btn-primary ml-1   save-category"
                                            data-dismiss="modal">Save
                                    </button>
                                </div>

                            </div> <!-- end modal-body-->
                        </div> <!-- end modal-content-->
                    </div> <!-- end modal dialog-->
                </div>
                <!-- end modal-->
            </div>
            <!-- end col-12 -->
        </div> <!-- end row -->

    </div> <!-- container -->
{% endblock %}


<!-- END wrapper -->


{% block js-footer %}
    <!-- third party js -->
    <script src="{% static 'javascript/jquery-ui.min.js' %}"></script>
    <script src="{% static 'javascript/fullcalendar.min.js' %}"></script>
    <!-- third party js ends -->

    <!-- demo app -->
    <script src="{% static 'javascript/demo.calendar.js' %}"></script>
    <!-- end demo js-->

{% endblock %}

templates/base-left-sidebar.html
{% load static %}

<!-- ========== Left Sidebar Start ========== -->
<div class="left-side-menu">

    <div class="slimscroll-menu">
        <!-- LOGO -->
        <a href="{% url 'index' %}" class="logo text-center mb-4">
                <span class="logo-lg mr-3 mt-1">
                    <img src="{% static 'htmlimg/logo.svg' %}" alt="" height="40">
                </span>
        </a>

        <!--- Sidemenu -->
        <ul class="metismenu side-nav">
            <li class="side-nav-title side-nav-item">Navigation</li>
            <li hidden class="side-nav-item">
                <a href="#" class="side-nav-link">
                    <i class="dripicons-meter"></i>
                    <span hidden class="badge badge-success float-right">7</span>
                    <span> Dashboard </span>
                </a>
            </li>

            <li class="side-nav-item">
                <a href="{% url 'asset:index' %}" class="side-nav-link">
                    <i class="dripicons-device-desktop"></i>
                    <span> 设备台账 </span>
                </a>
            </li>

            <li class="side-nav-item">
                <a href="{% url 'asset:mine' %}" class="side-nav-link">
                    <i class="dripicons-document"></i>
                    <span> 我的业务 </span>
                </a>
            </li>

            <li class="side-nav-item">
                <a href="#" class="side-nav-link">
                    <i class="dripicons-archive"></i>
                    <span> 业务办理 </span>
                    <span class="menu-arrow"></span>
                </a>
                <ul class="side-nav-second-level" >
                    <li>
                        <a href="{% url 'asset:create' %}">设备建账</a>
                    </li>
                    <li>
                        <a href="{% url 'asset:return-index' %}">设备归还</a>
                    </li>
                </ul>
            </li>

            <li class="side-nav-item">
                <a href="{% url 'review:index' %}" class="side-nav-link">
                    <i class="dripicons-folder-open"></i>
                    <span> 业务审批 </span>
                </a>
            </li>

            <li class="side-nav-item">
                <a href="#" class="side-nav-link">
                    <i class="dripicons-checklist"></i>
                    <span> 设备报表 </span>
                    <span class="menu-arrow"></span>
                </a>
                <ul class="side-nav-second-level">
                    <li>
                        <a href="{% url 'asset:create-table' %}">设备建账表</a>
                    </li>
                    <li>
                        <a href="{% url 'asset:scrap-table' %}">设备报废表</a>
                    </li>
                    <li>
                        <a href="{% url 'asset:fix-table' %}">设备报修表</a>
                    </li>
                    <li>
                        <a href="{% url 'asset:borrow-return-table' %}">设备借还表</a>
                    </li>
                </ul>

            </li>

            <li class="side-nav-item">
                <a href="#" class="side-nav-link">
                    <i class="dripicons-rocket"></i>
                    <span> 附加程序 </span>
                    <span class="menu-arrow"></span>
                </a>
                <ul class="side-nav-second-level">
                    <li>
                        <a href="{% url 'user:calendar' %}">日程表</a>
                    </li>
                </ul>
            </li>

            <li class="side-nav-item">
                <a href="#" class="side-nav-link">
                    <i class="mdi mdi-settings-outline"></i>
                    <span> 系统管理 </span>
                    <span class="menu-arrow"></span>
                </a>
                <ul class="side-nav-second-level">
                    <li>
                        <a href="{% url 'user:index' %}">用户管理</a>
                    </li>
                    <li>
                        <a href="{% url 'user:groups' %}">角色组管理</a>
                    </li>
                    <li>
                        <a href="{% url 'department:index' %}">部门管理</a>
                    </li>
                </ul>
            </li>
            <li class="side-nav-item">
                <a href="#" class="side-nav-link">
                    <i class="mdi mdi-dots-horizontal"></i>
                    <span> 其他 </span>
                    <span class="menu-arrow"></span>
                </a>
                <ul class="side-nav-second-level">
                    <li>
                        <a href="{% url 'user:profile' user.id %}">我的账号</a>
                    </li>
                    <li>
                        <a href="{% url 'faq' %}">FAQ 疑难解答</a>
                    </li>
                </ul>
            </li>
        </ul>
        <!-- End Sidebar -->
        <div class="clearfix"></div>
    </div>
    <!-- Sidebar -left -->
</div>
<!-- Left Sidebar End -->

templates/base-modal-warning.html
{% load static %}

<div id="{{id}}" class="modal fade" tabindex="-1" role="dialog"
     aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body p-4">
                <div class="text-center">
                    <i class="dripicons-warning h1 text-warning"></i>
                    <h4 class="mt-2">Warning</h4>
                    <p class="mt-3">{{ msg }}</p>
                    <button type="button" class="btn btn-secondary my-2 mr-3"
                            data-dismiss="modal" id="{{ id }}-cancel">Cancel
                    </button>
                    <button type="button" class="btn btn-warning my-2" id="{{ id }}-continue">Continue
                    </button>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/base-modal.html
{% load static %}

<!-- {{ id }} content -->
<div id="{{ id }}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="{{ id }}-label">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            {% block header %}
                <div class="modal-header">
                    <div class="text-center ml-auto">
                        <img src="{% static 'htmlimg/logo-dark.svg' %}" alt="" height="50">
                    </div>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
            {% endblock %}

            {% block body %}
            {% endblock %}
        </div>
    </div>
</div>
<!-- /.modal content -->
<!-- {{ id }} script -->
{% block js %}
{% endblock %}
<!-- /.modal script -->

templates/base-page-title.html
{% load static %}
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                {% block title-right %}
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{% url 'index' %}">Arcadia</a></li>
                        {% if sec_title %}
                            <li class="breadcrumb-item"><a href="{{ sec_url }}">{{ sec_title }}</a></li>
                        {% endif %}
                        <li class="breadcrumb-item active">{{ title_name | capfirst }}</li>
                    </ol>
                {% endblock %}
            </div>
            {% block title %}
                <h4 class="page-title">{{ title_name | capfirst }}</h4>
            {% endblock %}
        </div>
    </div>
</div>
<!-- end page title -->

templates/base-right-sidebar.html
{% load static %}
<!-- Right Sidebar -->
<div class="right-bar">

    <div class="rightbar-title">
        <a href="#" class="right-bar-toggle float-right">
            <i class="dripicons-cross noti-icon"></i>
        </a>
        <h5 class="m-0">Settings</h5>
    </div>

    <div class="slimscroll-menu">

        <!-- Settings -->
        <hr class="mt-0"/>
        <h5 class="pl-3">Basic Settings</h5>
        <hr class="mb-0"/>

        <div class="p-3">
            <div class="custom-control custom-checkbox mb-2">
                <input type="checkbox" class="custom-control-input" id="notifications-check" checked>
                <label class="custom-control-label" for="notifications-check">Notifications</label>
            </div>

            <div class="custom-control custom-checkbox mb-2">
                <input type="checkbox" class="custom-control-input" id="api-access-check">
                <label class="custom-control-label" for="api-access-check">API Access</label>
            </div>

        </div>


        <!-- Timeline -->
        <hr class="mt-0"/>
        <h5 class="pl-3">Recent Activity</h5>
        <hr class="mb-0"/>
        <div class="pl-2 pr-2">
            <div class="timeline-alt">
                <div class="timeline-item">
                    <i class="mdi mdi-upload bg-info-lighten text-info timeline-icon"></i>
                    <div class="timeline-item-info">
                        <a href="#" class="text-info font-weight-bold mb-1 d-block">You sold an
                            item</a>
                        <small>Paul Burgess just purchased “Arcadia - Admin Dashboard”!</small>
                        <p>
                            <small class="text-muted">5 minutes ago</small>
                        </p>
                    </div>
                </div>

                <div class="timeline-item">
                    <i class="mdi mdi-airplane bg-primary-lighten text-primary timeline-icon"></i>
                    <div class="timeline-item-info">
                        <a href="#" class="text-primary font-weight-bold mb-1 d-block">Product on the
                            Bootstrap Market</a>
                        <small>Dave Gamache added
                            <span class="font-weight-bold">Admin Dashboard</span>
                        </small>
                        <p>
                            <small class="text-muted">30 minutes ago</small>
                        </p>
                    </div>
                </div>

                <div class="timeline-item">
                    <i class="mdi mdi-microphone bg-info-lighten text-info timeline-icon"></i>
                    <div class="timeline-item-info">
                        <a href="#" class="text-info font-weight-bold mb-1 d-block">Robert Delaney</a>
                        <small>Send you message
                            <span class="font-weight-bold">"Are you there?"</span>
                        </small>
                        <p>
                            <small class="text-muted">2 hours ago</small>
                        </p>
                    </div>
                </div>

                <div class="timeline-item">
                    <i class="mdi mdi-upload bg-primary-lighten text-primary timeline-icon"></i>
                    <div class="timeline-item-info">
                        <a href="#" class="text-primary font-weight-bold mb-1 d-block">Audrey
                            Tobey</a>
                        <small>Uploaded a photo
                            <span class="font-weight-bold">"Error.jpg"</span>
                        </small>
                        <p>
                            <small class="text-muted">14 hours ago</small>
                        </p>
                    </div>
                </div>

                <div class="timeline-item">
                    <i class="mdi mdi-upload bg-info-lighten text-info timeline-icon"></i>
                    <div class="timeline-item-info">
                        <a href="#" class="text-info font-weight-bold mb-1 d-block">You sold an
                            item</a>
                        <small>Paul Burgess just purchased “Arcadia - Admin Dashboard”!</small>
                        <p>
                            <small class="text-muted">1 day ago</small>
                        </p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<!-- /Right-bar -->

templates/base-sidebar.html
{% extends "base-layer.html" %}
{% load static %}

{% block main %}
    {% include 'base-left-sidebar.html' %}

    <!-- Start Page Content here -->
    <div class="content-page">
        <div class="content">
            {% include 'base-top-sidebar.html' %}
            {% block content %}
            {% endblock %}
        </div><!-- content -->
        {% include 'module-footer-contact.html' %}
    </div>
    <!-- End Page content -->

{#    {% include 'base-right-sidebar.html' %}#}
{% endblock %}

templates/faq.html
{% extends 'base-sidebar.html' %}
{% load static %}
{% block content %}
    <div class="mt-5 mb-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="text-center">
                                <h3 class="">常见疑难解答</h3>
                                <a type="button" href="mailto:arcadia_ems@163.com"
                                   class="btn btn-success btn-sm mt-2"><i
                                        class="mdi mdi-email-outline mr-1"></i> Email us
                                </a>
                            </div>
                        </div><!-- end col -->
                    </div><!-- end row -->

                    <div class="row pt-5">
                        <div class="col-lg-10 offset-lg-1">
                            {% for faq in faqs %}
                                <!-- Question/Answer -->
                                <div>
                                    <div class="faq-question-q-box">Q.</div>
                                    <h4 class="faq-question">{{ faq.question }}</h4>
                                    <p class="faq-answer mb-4">{{ faq.answer }}</p>
                                </div>
                            {% endfor %}
                        </div>
                        <!--/col-md-5 -->
                    </div>

                </div> <!-- end col -->
            </div>
            <!-- end row -->
        </div>
    </div>
    <!-- end page -->
{% endblock %}

templates/maintenance.html
{% extends 'base-sidebar.html' %}
{% load static %}
{% block content %}
    <div class="mt-5 mb-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">

                    <div class="text-center">
                        <img src="{% static 'htmlimg/maintenance.svg' %}" height="140" alt="">
                        <h3 class="mt-4">This page is under <strong>Maintenance</strong></h3>
                        <p class="text-muted">Sorry, we'll be back shortly.</p>

                        <div class="row mt-5">
                            <div class="col-md-4">
                                <div class="text-center mt-3 pl-1 pr-1">
                                    <i class="dripicons-jewel bg-primary maintenance-icon text-white mb-2"></i>
                                    <h5 class="text-uppercase">Why is the page down?</h5>
                                    <p class="text-muted">
                                        Under development, fatal bug, ...
                                    </p>
                                </div>
                            </div> <!-- end col-->
                            <div class="col-md-4">
                                <div class="text-center mt-3 pl-1 pr-1">
                                    <i class="dripicons-clock bg-primary maintenance-icon text-white mb-2"></i>
                                    <h5 class="text-uppercase">What is the Downtime?</h5>
                                    <p class="text-muted">别问，问就是在写了（</p>
                                    <a href="https://devcloud.huaweicloud.com/codehub/project/6784eb1f60f94d26a7cecc7868cab109/codehub/660645/chart">
                                        追踪进度（
                                    </a>
                                </div>
                            </div> <!-- end col-->
                            <div class="col-md-4">
                                <div class="text-center mt-3 pl-1 pr-1">
                                    <i class="dripicons-question bg-primary maintenance-icon text-white mb-2"></i>
                                    <h5 class="text-uppercase">Do you need Support?</h5>
                                    <p class="text-muted">Please contact <a href="https://github.com/biopuppet/"
                                                                            class="text-muted font-weight-bold">biopuppet</a>
                                    </p>
                                </div>
                            </div> <!-- end col-->
                        </div> <!-- end row-->
                    </div> <!-- end /.text-center-->

                </div> <!-- end col -->
            </div>
            <!-- end row -->
        </div>
    </div>
    <!-- end page -->
{% endblock %}

templates/module-footer-contact.html
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                2020 © Arcadia EMS - 爽粉后援会
            </div>
            <div class="col-md-6">
                <div class="text-md-right footer-links d-none d-sm-block">
                    <a href="{% url 'faq' %}">FAQs</a>
                    <a href="{% url 'maintained' %}">About</a>
                    <a href="https://github.com/biopuppet">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/module-footer.html
<footer class="footer footer-alt">
    2020 © Arcadia EMS - 爽粉后援会
</footer>

templates/pages-login.html
{% extends "base-page-card.html" %}
{% load static %}

{% block card-body %}
    <div class="card-body p-4">
        <div class="text-center w-80 m-auto">
            <h4 class="text-dark-50 text-center mt-0 font-weight-bold">Sign In</h4>
            <p class="text-muted mb-4">Enter your username and password to sign in.</p>
        </div>

        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group mb-3">
                <label for="username">Username</label>
                <input name="username" class="form-control" id="username"
                       required="" placeholder="Enter your username">
            </div>

            <div class="form-group mb-3">
                <a href="{% url 'user:recover-password' %}" class="text-muted float-right"><small>Forgot your
                    password?</small></a>
                <label for="password">Password</label>
                <input name="password" class="form-control" type="password" required=""
                       id="password" placeholder="Enter your password">
            </div>

            {% if msg %}
                <p class="alert alert-warning">{{ msg }}</p>
            {% endif %}

            <div class="form-group mb-0 text-center">
                <button class="btn btn-primary" type="submit"> Sign In</button>
            </div>
        </form>
    </div> <!-- end card-body -->
{% endblock %}

{% block under-card %}
{% endblock %}