ArcadiaEMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from asset.views import AssetIndexView
from .settings import DEBUG
from user import views as user_views
from django.conf import settings
from django.conf.urls.static import static

from .views import page_error, page_not_found

urlpatterns = \
    [
        path('user/', include('user.urls', namespace='user')),
        path('department/', include('department.urls', namespace='department')),
        path('asset/', include('asset.urls', namespace='asset')),
        path('review/', include('review.urls', namespace='review')),

        path('', AssetIndexView.as_view(), name='index'),
        path('login/', user_views.LoginView.as_view(), name='login'),
        path('logout/', user_views.LogoutView.as_view(), name='logout'),
        path('maintained/', auth_views.TemplateView.as_view(template_name='maintenance.html'),
             name='maintained'),
        path('faq/', user_views.FaqView.as_view(), name='faq'),
        path('admin/', admin.site.urls),
        # path('ui/', include('system.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found
handler500 = page_error

if DEBUG:
    urlpatterns += [
        path('404/', handler404, name='404'),
        path('500/', handler500, name='500'),
    ]

user/urls.py
from django.urls import path

from user.views import *

app_name = 'user'

urlpatterns = [
    # path('user/', ),
    path('', UserIndexView.as_view(), name='index'),
    path('<int:user_id>', UserProfileView.as_view(), name='profile'),
    path('create-user/', UserCreateView.as_view(), name='create-user'),
    path('delete-user/<int:user_id>', DeleteUserView.as_view(), name='delete-user'),
    path('update-user/', UpdateUserView.as_view(), name='update-user'),

    path('toggle-user-status/<int:user_id>', ToggleUserStatusView().as_view(), name='toggle-user-status'),

    path('change-password/<int:user_id>', UserChangePasswordView.as_view(), name='change-password'),
    path('recover-password/', UserRecoverPasswordView.as_view(), name='recover-password'),

    path('calendar/', UserCalendarView.as_view(), name='calendar'),
    path('group/', UserGroupsView.as_view(), name='groups'),
    path('group/create', UserCreateGroupView.as_view(), name='create-group'),
    path('group/<int:group_id>/change', UserChangeGroupView.as_view(), name='change-group'),
    path('group/<int:group_id>/delete', UserDeleteGroupView.as_view(), name='delete-group'),
]

user/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.db import models
from django.contrib.auth.models import AbstractUser

from department.models import Department


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, email, password, **extra_fields)


class UserProfile(AbstractUser):
    fullname = models.CharField(max_length=30, blank=True, verbose_name="Full Name")
    phone = models.CharField(max_length=13, default="", verbose_name="Mobile Number")
    image = models.ImageField(upload_to="image/%Y/%m", default="image/default.jpg",
                              max_length=100, null=True, blank=True)
    department = models.ForeignKey(Department, related_name='users', null=True, blank=True, on_delete=models.SET_NULL,
                                   verbose_name="部门")
    # post = models.CharField(max_length=50, null=True, blank=True, verbose_name="职位")
    # superior = models.ForeignKey("self", null=True, blank=True, on_delete=models.SET_NULL, verbose_name="上级主管")
    # roles = models.ManyToManyField("Role", verbose_name="角色", blank=True)
    objects = UserManager()

    class Meta:
        verbose_name = "User Profile"
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.username.__str__()


class Faq(models.Model):
    question = models.CharField(max_length=100, verbose_name='Question')
    answer = models.TextField(verbose_name='Answer')

user/views.py
import json
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.models import Group
from django.core.exceptions import ObjectDoesNotExist
from django.forms import model_to_dict
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View

from ArcadiaEMS.mixin import LoginRequiredMixin
from ArcadiaEMS.views import page_not_found
from ArcadiaEMS.email import send_email
from user.forms import LoginForm, UserCreateForm, UserChangePasswordForm, UserUpdateForm, GroupCreationForm
from user.models import UserProfile, Faq
from user.serializers import UserProfileSerializer

User = get_user_model()


class IndexView(LoginRequiredMixin, View):

    def get(self, request):
        return render(request, 'dashboard.html')


class LoginView(View):

    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, 'pages-login.html')
        else:
            return HttpResponseRedirect('/')

    def post(self, request):
        redirect_to = request.GET.get('next', '/')
        login_form = LoginForm(request.POST)
        ret = dict()
        if login_form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(redirect_to)
                else:
                    ret['msg'] = 'This user is inactive, please contact admin.'
            else:
                ret['msg'] = 'Incorrect username or password!'
        else:
            ret['msg'] = 'username or password can\'t be empty!'
        return render(request, 'pages-login.html', ret)


class LogoutView(View):

    def get(self, request):
        logout(request)
        return render(request, 'pages-logout.html')


class UserProfileView(LoginRequiredMixin, View):

    def get(self, request, user_id):
        requested_user = get_object_or_404(User, pk=int(user_id))
        request_user = request.user
        # @TODO: Add permission check
        # if request_user != requested_user:
        #     return page_not_found(request)
        # else:
        user_dict = model_to_dict(request_user)
        user_update_form = UserUpdateForm(auto_id="form-update-user-%s", label_suffix='', initial=user_dict)
        ret = {
            'user': requested_user,
            'user_update_form': user_update_form,
        }

        return render(request, 'user/profile.html', ret)


class UserIndexView(LoginRequiredMixin, View):

    def get(self, request):
        users = UserProfile.objects.all()
        user_create_form = UserCreateForm(auto_id="form-create-user-%s", label_suffix='')
        user_update_form = UserUpdateForm(auto_id="form-update-user-%s", label_suffix='')
        ret = {
            'user_create_form': user_create_form,
            'user_update_form': user_update_form,
        }
        return render(request, 'user/index.html', ret)

    def post(self, request):
        user_list = []
        for user in User.objects.all():
            user_list.append({
                'id': user.id,
                'username': user.username,
                'fullname': user.fullname,
                'email': user.email,
                'phone': user.phone,
                'image': str(user.image),
                'is_active': user.is_active,
                'department': str(user.department),
            })
        return HttpResponse(json.dumps(user_list), content_type='application/json')


class UserCreateView(LoginRequiredMixin, View):

    def post(self, request):
        if request.is_ajax():
            user_create_form = UserCreateForm(request.POST)
            users = UserProfile.objects.all()
            if user_create_form.is_valid():
                user_create_form.save()
                ret = {
                    'status': 'success',
                }
            else:
                ret = {
                    'status': 'fail',
                    'errors': user_create_form.errors.as_ul(),
                }
            return HttpResponse(json.dumps(ret), content_type='application/json')


class UpdateUserView(LoginRequiredMixin, View):

    def get(self, request):
        if request.is_ajax() and 'user_id' in request.GET and int(request.GET['user_id']) > 0:
            user_id = request.GET['user_id']
            user = User.objects.get(id=user_id)
            user_data = UserProfileSerializer(instance=user, many=False).data
            ret = {
                'status': 'success',
                'data': user_data,
            }
            return HttpResponse(json.dumps(ret), content_type='application/json')

    def post(self, request):
        user_id = request.POST.get('id')
        user = get_object_or_404(User, pk=int(user_id))
        user_update_form = UserUpdateForm(request.POST, instance=user)
        if user_update_form.is_valid():
            user_update_form.save()
            ret = {'status': 'success'}
        else:
            ret = {
                'status': 'fail',
                'errors': user_update_form.errors.as_ul(),
            }
        return HttpResponse(json.dumps(ret), content_type='application/json')


class UserChangePasswordView(LoginRequiredMixin, View):

    def post(self, request, user_id):
        if 'id' in request.POST and int(request.POST['id']) == user_id:
            user = get_object_or_404(User, pk=int(request.POST['id']))
        else:
            raise page_not_found(request)
        form = UserChangePasswordForm(request.POST)
        if form.is_valid():
            new_password = request.POST['new_password']
            user.set_password(new_password)
            user.save()
            ret = {
                'status': 'success',
            }
        else:
            ret = {
                'status': 'fail',
                'errors': form.errors.as_text()
            }
        return HttpResponse(json.dumps(ret), content_type='application/json')


class ToggleUserStatusView(LoginRequiredMixin, View):

    def get(self, request, user_id):
        if user_id > 0:
            user = get_object_or_404(User, pk=int(user_id))
            user.is_active = not user.is_active
            user.save()
        return HttpResponseRedirect(reverse('user:index'))


class DeleteUserView(LoginRequiredMixin, View):

    def get(self, request, user_id):
        if user_id > 0:
            User.objects.filter(id=user_id).delete()
        return redirect('user:index')


class UserCalendarView(LoginRequiredMixin, View):

    def get(self, request):
        return render(request, 'apps-calendar.html')


class UserGroupsView(LoginRequiredMixin, View):

    def get(self, request):
        groups = Group.objects.all()
        return render(request, 'user/groups.html', {'groups': groups})


class UserCreateGroupView(LoginRequiredMixin, View):

    def get(self, request):
        form = GroupCreationForm()
        return render(request, 'user/group-create.html', {'form': form})

    def post(self, request):
        form = GroupCreationForm(request.POST)
        ret = {'form': GroupCreationForm(), }
        if form.is_valid():
            group = form.save()
            ret.update({
                'msg': '成功创建角色组: {}'.format(group)
            })
        else:
            ret.update({
                'error_msg': form.errors.as_ul()
            })
        return render(request, 'user/group-create.html', ret)


class UserChangeGroupView(LoginRequiredMixin, View):

    def get(self, request, group_id):
        group = get_object_or_404(Group, pk=group_id)
        form = GroupCreationForm(instance=group)
        return render(request, 'user/group-change.html', {'form': form, 'group': group})

    def post(self, request, group_id):
        group = get_object_or_404(Group, pk=group_id)
        form = GroupCreationForm(request.POST, instance=group)
        ret = {'form': form, 'group': group}
        if form.is_valid():
            group = form.save()
            ret.update({
                'msg': '成功更改角色组: {}'.format(group),
            })
        else:
            ret.update({
                'error_msg': form.errors.as_ul(),
            })
        return render(request, 'user/group-change.html', ret)


class UserDeleteGroupView(LoginRequiredMixin, View):

    def get(self, request, group_id):
        group = get_object_or_404(Group, pk=group_id)
        group.delete()
        return redirect('user:groups')


class UserRecoverPasswordView(View):

    def get(self, request):
        return render(request, 'user/recover-password.html')

    def post(self, request):
        if 'email' in request.POST and request.POST['email']:
            user_email = request.POST['email']
            token = User.objects.make_random_password()
            """ 
            Do not use the shortcut below, coz user shouldn't know if the email refs an user.
            user = get_object_or_404(User, email=user_email)
            """
            try:
                user = User.objects.get(email=user_email)
                name = user.fullname or user.username
                print(name)
                send_email(request, to=user_email, token=token, name=name)
                user.set_password(token)
                user.save()
            except ObjectDoesNotExist:
                pass
            # No user with this email. Just pretend we've sent.
            return render(request, 'user/recover-password.html', {'sent': True})
        else:
            error_msg = 'Please enter your email.'
            return render(request, 'user/recover-password.html', {'error_msg': error_msg})


class FaqView(LoginRequiredMixin, View):

    def get(self, request):
        faqs = Faq.objects.all()

templates/user/group-change.html
{% extends "base-sidebar.html" %}
{% load static %}

{% block content %}
    <!-- Start Content-->
    <div class="container-fluid">
        {% include 'base-page-title.html' with title_name='Change Group' sec_title="Groups" sec_url="/user/group/" %}
        {% if msg %}
            <div class="alert alert-success" role="alert">
                {{ msg }}
            </div>
        {% endif %}
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form action="{% url 'user:change-group' group.id %}" method="post" class="pl-3 pr-3">
                            {% csrf_token %}
                            {% for item in form %}
                                <div class="form-group mb-3">
                                    {{ item.label_tag }}
                                    {{ item }}
                                    {{ item.errors }}
                                </div>
                            {% endfor %}
                            {% if error_msg %}
                                <p class="alert alert-warning">{{ error_msg }}</p>
                            {% endif %}
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <div class="text-left">
                                        <a href="{% url 'user:delete-group' group.id %}" class="btn btn-danger"
                                           type="button">Delete
                                            Group</a>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="text-sm-right">
                                        <button class="btn btn-primary" type="submit">Update Group</button>
                                    </div>
                                </div>
                            </div>

                        </form>

                    </div> <!-- end card body-->
                </div> <!-- end card -->
            </div><!-- end col-->
        </div>
        <!-- end row-->
    </div> <!-- container -->
{% endblock %}

templates/user/groups.html
{% extends "base-sidebar.html" %}
{% load static %}

{% block css %}
    <!-- third party css -->
    <link href="{% static 'css/dataTables.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/buttons.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/select.bootstrap4.css' %}" rel="stylesheet" type="text/css"/>
    <!-- third party css end -->
{% endblock %}

{% block content %}
    <!-- Start Content-->
    <div class="container-fluid">
        {% include 'base-page-title.html' with title_name='Groups' %}

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <a href="{% url 'user:create-group' %}" type="button" class="btn btn-primary mb-3">
                            <i class="mdi mdi-account-multiple-plus-outline mr-1"></i> New Group
                        </a>
                        <table id="basic-datatable" class="table table-striped dt-responsive nowrap">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th class="sorting_desc_disabled sorting_asc_disabled">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for group in groups %}
                                <tr>
                                    <td>{{ group.id }}</td>
                                    <td>{{ group.name }}</td>
                                    <td class="table-action">
                                        <a href="{% url 'user:change-group' group.id %}" class="action-icon">
                                            <i class="mdi mdi-pencil"></i></a>
                                        <a href="{% url 'user:delete-group' group.id %}" class="action-icon">
                                            <i class="mdi mdi-delete"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div> <!-- end card body-->
                </div> <!-- end card -->
            </div><!-- end col-->
        </div>
        <!-- end row-->
    </div> <!-- container -->
{% endblock %}


{% block js-footer %}
    <!-- third party js -->
    <script src="{% static 'javascript/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'javascript/dataTables.bootstrap4.js' %}"></script>
    <script src="{% static 'javascript/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'javascript/responsive.bootstrap4.min.js' %}"></script>
    <!-- third party js ends -->
    
    <!-- demo app -->
    <script src="{% static 'javascript/demo.datatable-init2.js' %}"></script>
    <!-- end demo js-->
{% endblock %}

templates/user/profile.html
{% extends "base-sidebar.html" %}
{% load static %}

{% block content %}
    <!-- Start Content-->
    <div class="container-fluid">
        {% include 'base-page-title.html' with title_name='Profile' %}

        <div class="row">
            <div class="col-sm-12">
                <!-- Profile -->
                <div class="card bg-primary">
                    <div class="card-body profile-user-box">
                        <span class="float-left m-2"><img src="/media/{{ user.image }}"
                                                          style="height: 100px;" alt=""
                                                          class="rounded-circle img-thumbnail"></span>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="media-body">
                                    <h4 class="mt-1 mb-1 text-white">{{ user.fullname|default:'请填写姓名' }}</h4>
                                    <p class="font-13 text-white-50">@{{ user.username }}</p>
                                </div> <!-- end media-body-->
                                <ul class="mb-0 text-light">
                                    <li class="mr-3">
                                        <h5 class="mb-1">{{ user.email|default:'Σ(⊙▽⊙"竟然没有邮箱，你干了什么' }}</h5>
                                    </li>
                                    <li class="">
                                        <h5 class="mb-1">{{ user.phone|default:'qwq没有手机号...' }}</h5>
                                    </li>
                                </ul>
                            </div> <!-- end col-->
                            <!-- Change password modal content -->
                            <div id="change-password-modal" class="modal fade">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-body">
                                            <div class="text-center mt-2 mb-4">
                                                <a href="" class="text-success">
                                                    <span><img src="{% static 'htmlimg/logo-dark.svg' %}" alt=""
                                                               height="50"></span>
                                                </a>
                                            </div>

                                            <form id="form-change-password" class="pl-3 pr-3">
                                                {% csrf_token %}
                                                <input type="hidden" name='id' value="{{ user.id }}"/>
                                                <div class="form-group">
                                                    <label>Current Password</label>
                                                    <input name="current_password" class="form-control" type="password"
                                                           required="" minlength="6" maxlength="20"
                                                           placeholder="Current Password">
                                                </div>
                                                <div class="form-group">
                                                    <label>New Password</label>
                                                    <input name="new_password" class="form-control" type="password"
                                                           required="" minlength="6" maxlength="20"
                                                           placeholder="New Password">
                                                </div>
                                                <div class="form-group">
                                                    <label>New Password (again)</label>
                                                    <input name="confirm_password" class="form-control" type="password"
                                                           required="" minlength="6" maxlength="20"
                                                           placeholder="New Password (again)">
                                                </div>
                                                <div class="form-group text-center">
                                                    <button class="btn btn-info mr-3" data-dismiss="modal">Cancel
                                                    </button>
                                                    <button id="btn-change-password" class="btn btn-danger"
                                                            type="submit">Confirm
                                                    </button>
                                                </div>
                                            </form>
                                        </div>
                                    </div><!-- /.modal-content -->
                                </div><!-- /.modal-dialog -->
                            </div>
                            <!-- /.modal -->
                            <div class="col-sm-6 text-right">
                                <button type="button" class="btn btn-danger" data-toggle="modal"
                                        data-target="#change-password-modal">Change Password
                                </button>
                            </div>
                        </div> <!-- end row -->
                    </div> <!-- end card-body/ profile-user-box-->
                </div><!--end profile/ card -->
            </div> <!-- end col-->
        </div>
        <!-- end row -->

        <div class="row">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h4 class="header-title mb-3">Basic Profile</h4>

                        <form id="form-update-user" onsubmit="return false" action="" method="post" novalidate>
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.path }}">
                            <input type="hidden" name="{{ user_update_form.id.name }}"
                                   id="{{ user_update_form.id.id_for_label }}" value="{{ user.id }}">

                            <div class="form-group mb-3">
                                <label for="validationCustomUsername">Username</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="inputGroupPrepend">@</span>
                                    </div>
                                    <input name="username" type="text" class="form-control"
                                           id="validationCustomUsername"
                                           placeholder="Username" aria-describedby="inputGroupPrepend"
                                           value="{{ user.username }}" readonly>
                                </div>
                            </div>

                            <div class="form-group mb-3">
                                {{ user_update_form.fullname.label_tag }}
                                {{ user_update_form.fullname }}
                                {{ user_update_form.fullname.errors }}
                            </div>

                            <div class="form-group mb-3">
                                {{ user_update_form.phone.label_tag }}
                                {{ user_update_form.phone }}
                                {{ user_update_form.phone.errors }}
                            </div>

                            <div class="form-group mb-3">
                                <label for="validationCustom03">Email</label>
                                <input name="email" type="email" class="form-control" id="validationCustom03"
                                       placeholder="Email"
                                       value="{{ user.email }}" readonly>
                            </div>
                            <div id="error-msg"></div>
                            <div class="text-center">
                                <button class="btn btn-primary" type="submit">Update Profile</button>
                            </div>
                        </form>
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col-->
        </div>
        <!-- end row -->
    </div> <!-- container -->
{% endblock %}


{% block javascript %}
    <!-- demo app -->
    <script src="{% static 'javascript/demo.profile.js' %}"></script>
    <!-- end demo js-->
{% endblock %}
{% block js-footer %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#form-update-user').submit(function () {
                $.ajax({
                    url: '{% url 'user:update-user' %}',
                    type: 'POST',
                    data: $("#form-update-user").serialize(),
                    cache: false,
                    async: true,
                    success: function (msg) {
                        if (msg.status === 'success') {
                            parent.location.reload();
                        } else {
                            console.log(msg.errors);
                            $('#error-msg').html(msg.errors);
                            $('#error-msg').addClass('alert alert-warning');
                        }
                    },
                    complete: function (XMLHttpRequest) {
                    }
                });
                return false; // !important! or the form will be posted twice
            });
            $('#form-change-password').submit(function () {
                $.ajax({
                    url: '{% url 'user:change-password' user.id %}',
                    type: 'POST',
                    data: $("#form-change-password").serialize(),
                    cache: false,
                    async: true,
                    success: function (msg) {
                        if (msg.status === 'success') {
                            parent.location.reload();
                        } else {
                            console.log(msg.errors);
                            alert(msg.errors)
                        }
                    },
                    complete: function (XMLHttpRequest) {
                    }
                });
                return false; // !important! or the form will be posted twice
            });

        });
    </script>
{% endblock %}